### ISSUE TITLE
French Translation

### ISSUE THREAD

**Issue by fvsch** [CoralineAda/postmeritocracy#17]
Opening this issue to coordinate efforts of people who want to see a French translation happen.

Personally, I’d like to see a professional translation and am considering paying for it. This seems to be in the spirit of this manifesto (e.g. “Our success and value is not dependent on exerting all of our energy on contributing to software”). I can reach to at least one English-to-French translator friend.

**Comment by rik** [comment]
Good idea. I'll contribute financially.

**Comment by CoralineAda** [comment]
That sounds amazing, thank you!

**Comment by fvsch** [comment]
Hi all, a translation is in progress.

**Comment by CoralineAda** [comment]
Thanks!

**Comment by guilhem** [comment]
@fvsch state? :)
I can help (myself or financially).

**Comment by fvsch** [comment]
Hi. I received the finished translation just before a very busy time for me, so haven’t gotten around to make the PR yet. Will do it at the end of the week.

**Comment by guilhem** [comment]
gentle ping :)

**Comment by ariasuni** [comment]
@fvsch Hi, it’s been a while since you said you have received the translation. Could you maybe send it here so somebody can make a PR, if you do not have the time to do it yourself?

**Comment by DuaelFr** [comment]
This translation looks really good to me (native French speaker).
Great job everyone!

I suggest to close this issue now it's done :)
