### ISSUE TITLE
I know how you can solve this.

### ISSUE THREAD

**Issue by redlagoon** [CoralineAda/postmeritocracy#33]
Get some medication.

**Comment by measlytwerp** [comment]
Why do you care so much that you came here to spam this issue tracker with your worthless opinion?

Could it be you're scared that maybe you're wrong and had to do some knee-jerk bullshit to put yourself at ease?

**Comment by sawyermade** [comment]
> Why do you care so much that you came here to spam this issue tracker with your worthless opinion?
> 
> Could it be you're scared that maybe you're wrong and had to do some knee-jerk bullshit to put yourself at ease?

I think you should take redlagoons advice and do society a favor by getting properly medicated.

**Comment by anarchistmae** [comment]
This place is like a honeypot for the worst people. Congratulations.

**Comment by sawyermade** [comment]
> This place is like a honeypot for the worst people. Congratulations.

I know, bc you ppl like you are here.

**Comment by michael-brade** [comment]
You know, redlagoon does have a point: why were issues 22 and 23 and 29 deleted (and issue 22 had verifiably no name-calling in it, just down-to-earth discussion, see #50), while this issue (and the other, still open, kind of useless issues) were not even closed? In fact, why delete at all? What's going on?

**Comment by ghost** [comment]
@redlagoon thanks for the laugh! That really made my day.
