### ISSUE TITLE
Where do I sign?

### ISSUE THREAD

**Issue by leafac** [CoralineAda/postmeritocracy#43]
The README mentions a Google Form, but I can’t find it on https://postmeritocracy.org

**Comment by stain** [comment]
The Google form <https://goo.gl/forms/9JT45K1iuKcBSPFj2> is referenced in some translations, but I believe you now just need to edit https://github.com/CoralineAda/postmeritocracy/blob/release/static/signatories.csv as a GitHub Pull Request. ("Edit" button should do it)

**Comment by leafac** [comment]
Thanks. Closed by #75.
